Laboratorio2ED1/Laboratorio2ED1/Models/Pais.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio2ED1.Models
{
    public class Pais : IComparable
    {
        string Nombre { get; set; }
        string grupo { get; set; }

        public int CompareTo(object obj)
        {
            if (obj == null) return 1;


            var Country = obj as Pais;
            if (Country != null)
            {
                return this.Nombre.CompareTo(Country.Nombre);
            }
            else
                throw new ArgumentException("No esta comparando los atributos correctos");
        }
    }
}

Laboratorio2ED1/Laboratorio2ED1/Controllers/PaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Laboratorio2ED1.DBContext;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Laboratorio2ED1.Clase;
using ArbolBinarioBu;

namespace Laboratorio2ED1.Controllers
{
    public class PaisController : Controller
    {
        public DefaultConnection db = DefaultConnection.getInstance;

        // GET: Pais
        public ActionResult IndexPais()
        {
            if (db.Orden == 0)
                return View(db.Paises.Infijo());
            else if (db.Orden == 1)
                return View(db.Paises.Prefijo());
            else
                return View(db.Paises.Postfijo());
        }

        public ActionResult OrdenWord(int id, int tipo)
        {
            try
            {
                db.Orden = id;

                if (tipo == 0)
                    return RedirectToAction(nameof(IndexPais));
                else if (tipo == 1)
                    return RedirectToAction(nameof(IndexNumero));
                else
                    return RedirectToAction(nameof(IndexWord));
            }
            catch
            {
                return View();
            }
        }

        // GET: String
        public ActionResult IndexWord()
        {
            if (db.Orden == 0)
                return View(db.Cadenas.Infijo());
            else if (db.Orden == 1)
                return View(db.Cadenas.Prefijo());
            else
                return View(db.Cadenas.Postfijo());
        }

        // GET: Int
        public ActionResult IndexNumero()
        {
            if (db.Orden == 0)
                return View(db.Numeros.Infijo());
            else if (db.Orden == 1)
                return View(db.Numeros.Prefijo());
            else
                return View(db.Numeros.Postfijo());
        }

        // GET: Pais/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pais/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include ="Nombre,grupo")]Models.Pais pais)
        {
            if (ModelState.IsValid)
            {
                db.Paises.Insertar(pais);

                return RedirectToAction(nameof(IndexPais));
            }

            return View(pais);
        }
        public ActionResult CreateInt()
        {
            return View();
        }
        // Post: Int/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateInt( FormCollection numero)
        {
            try
            {

                db.Numeros.Insertar(Convert.ToInt32(numero["valor"]));

                return RedirectToAction(nameof(IndexNumero));
            }
            catch
            {
                return View(numero);
            }
        }
        public ActionResult CreateString()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateString(FormCollection cadena)
        {
            try
            {
                db.Cadenas.Insertar(cadena["Valor"]);
                return RedirectToAction(nameof(IndexWord));
            }
            catch
            {
                return View(cadena["Valor"]);
            }
        }
        // GET: Pais/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pais/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pais/Delete/5
        public ActionResult Delete(string id, string group)
        {
            var aux = new Models.Pais
            {
                Nombre = id,
                grupo = group
            };
            if (aux.Nombre == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pais = db.Paises.Encontrar(aux).value;

            if (pais == null)
            {
                return HttpNotFound();
            }
            return View(pais);
        }

        // POST: Pais/Delete/5
        [HttpPost, ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCondirmed(string id, string group)
        {
            var _aux = new Models.Pais
            {
                Nombre = id,
                grupo = group
            };

            db.Paises.Eliminar(db.Paises.Encontrar(_aux).value);

            return RedirectToAction(nameof(IndexPais));
        }
        public ActionResult DeleteString(string id)
        {
            var valor = db.Cadenas.Encontrar(id).value;
          
            
            return View();
        }
        [HttpPost, ActionName(nameof(DeleteString))]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteString(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var valor = db.Cadenas.Encontrar(id);
                db.Cadenas.Eliminar(valor.value);
                
                return RedirectToAction(nameof(IndexWord));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult DeleteInt(int id)
        {
            var valor = db.Numeros.Encontrar(id).value;
            
            return View(valor);
        }
        [HttpPost,ActionName(nameof(DeleteInt))]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteInt(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var valor = db.Numeros.Encontrar(id);
                db.Numeros.Eliminar(valor.value);
                return RedirectToAction(nameof(IndexNumero));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult UploadInt()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadInt(HttpPostedFileBase file)
        {
            try
            {
                if (!file.FileName.EndsWith(".json"))
                    return View();
                if (file.ContentLength > 0)
                {
                    var json = new Archivo_Json<int>();
                    Nodo<int> raiz = json.Dato(file.InputStream);
                    db.Numeros.root = raiz;
                    return RedirectToAction("IndexNumero");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }

        [HttpGet]
        public ActionResult UploadPais()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadPais(HttpPostedFileBase file)
        {
            try
            {
                if (!file.FileName.EndsWith(".json"))
                    return View();
                if (file.ContentLength > 0)
                {
                    var json = new Archivo_Json<Models.Pais>();
                    Nodo<Models.Pais> raiz = json.Dato(file.InputStream);
                    db.Paises.root = raiz;
                    return RedirectToAction("IndexPais");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }

        [HttpGet]
        public ActionResult UploadString()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadStriing(HttpPostedFileBase file)
        {
            try
            {
                if (!file.FileName.EndsWith(".json"))
                    return View();
                if (file.ContentLength > 0)
                {
                    var json = new Archivo_Json<string>();
                    Nodo<string> raiz = json.Dato(file.InputStream);
                    db.Cadenas.root = raiz;
                    return RedirectToAction("IndexWord");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }
    }
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/Create.cshtml
@model Laboratorio2ED1.Models.Pais

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pais</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexPais", "Pais")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/CreateInt.cshtml
@{
    ViewBag.Title = "CreateInt";
}

<h2>CreateInt</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Entero</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Número", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("Valor", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexInt")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/CreateString.cshtml
@{
    ViewBag.Title = "CreateString";
}

<h2>CreateString</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cadena</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Cadena", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("Valor", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexWord")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/Delete.cshtml
@model Laboratorio2ED1.Models.Pais

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>¿Estas seguro de eliminar?</h3>
<div>
    <h4>Pais</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grupo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexPais")
        </div>
    }
</div>

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/DeleteInt.cshtml
@model System.Int32
@{
    ViewBag.Title = "DeleteInt";
}

<h2>DeleteInt</h2>
<h3>Estas seguro de eliminar</h3>
<div>
    <h4>Entero</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Número")
        </dt>

        <dd>

            @Html.DisplayName(Model.ToString())
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexNumero")
        </div>
    }
</div>

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/DeleteString.cshtml
@{
    ViewBag.Title = "DeleteString";
}

<h2>DeleteString</h2>
<h3>Estas seguro de eliminar</h3>
<div>
    <h4>Cadena</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Cadena")
        </dt>
      
        <dd>


        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexWord")
        </div>
    }
</div>

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/Index.cshtml
@model IEnumerable<Laboratorio2ED1.Models.Pais>

@{
    ViewBag.Title = "Index";
}

<h2>Paises</h2>

<p>
    @Html.ActionLink("Crear País", "Create", "Pais")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.grupo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grupo)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.Nombre, group=item.grupo })
        </td>
    </tr>
}

</table>

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/IndexNumero.cshtml
@model IEnumerable<int>

@{
    ViewBag.Title = "Index Numero";
}

<h2>IndexNumero</h2>

<p>
    @Html.ActionLink("Create New", "CreateInt") | 
    @Html.ActionLink("Orden InFijo", "OrdenWord", new { id = 0, tipo = 1 }) |
    @Html.ActionLink("Orden PreFijo", "OrdenWord", new { id = 1, tipo = 1 }) |
    @Html.ActionLink("Orden Postfijo", "OrdenWord", new { id = 2, tipo = 1 }) |
    @Html.ActionLink("Carga Archivo Json", "UploadInt")
</p>
<table class="table">
    <tr>
        <th> Numero</th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item)
            </td>

            <td>
                
                @Html.ActionLink("Delete", "DeleteInt", new { id = item })
            </td>
        </tr>
    }

</table>
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
    </script>
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/IndexPais.cshtml
@model IEnumerable<Laboratorio2ED1.Models.Pais>

@{
    ViewBag.Title = "IndexPais";
}

<h2>Paises</h2>

<p>
    @Html.ActionLink("Crear País", "Create", "Pais") |
    @Html.ActionLink("Orden InFijo", "OrdenWord", new { id = 0, tipo = 0 }) |
    @Html.ActionLink("Orden PreFijo", "OrdenWord", new { id = 1, tipo = 0 }) |
    @Html.ActionLink("Orden Postfijo", "OrdenWord", new { id = 2, tipo = 0 })|
    @Html.ActionLink("Carga Archivo Json", "UploadPais")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.grupo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grupo)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id = item.Nombre, group = item.grupo })
        </td>
    </tr>
}

</table>

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/IndexWord.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "IndexWord";
}

<h2>IndexWord</h2>
<p>
    @Html.ActionLink("Create New", "CreateString") |
    @Html.ActionLink("Orden InFijo", "OrdenWord", new { id = 0, tipo = 2 }) |
    @Html.ActionLink("Orden PreFijo", "OrdenWord", new { id = 1, tipo = 2 }) |
    @Html.ActionLink("Orden Postfijo", "OrdenWord", new { id = 2, tipo = 2 })|
    @Html.ActionLink("Carga Archivo Json", "UploadString")

</p>
<table class="table">
    <tr>
        <th> Cadena</th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item)
            </td>

            <td>
                
                @Html.ActionLink("Delete", "DeleteString", new { id= item })
            </td>
        </tr>
    }

</table>
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
    </script>
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/JsonFile.cshtml
@{
    ViewBag.Title = "JsonFile";
}

<h2>JsonFile</h2>

@using (Html.BeginForm("JsonFile",
                                  "Pais",
                                    FormMethod.Post,
                                    new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <label for="file">Cargar Archivo:</label>
    <input type="file" name="file" id="file" /><br><br>
    <input type="submit" value="Cargar Archivo" />
    <br><br>
    @ViewBag.Message
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/UploadInt.cshtml
@{
    ViewBag.Title = "UploadInt";
}

<h2>Carga Int</h2>
@using (Html.BeginForm("UploadInt", "Pais", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.TextBox("file", "", new { type = "file" }) <br />

    <input type="submit" value="Subir" />
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/UploadPais.cshtml
@{
    ViewBag.Title = "UploadPais";
}

<h2>UploadPais</h2>
@using (Html.BeginForm("UploadPais", "Pais", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.TextBox("file", "", new { type = "file" }) <br />

    <input type="submit" value="Subir" />
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio2ED1/Laboratorio2ED1/Views/Pais/UploadString.cshtml
@{
    ViewBag.Title = "UploadString";
}

<h2>UploadString</h2>
@using (Html.BeginForm("UploadString", "Pais", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.TextBox("file", "", new { type = "file" }) <br />

    <input type="submit" value="Subir" />
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}